include:
 - project: acc-co/devops/python/acc-py-gitlab-ci-templates
   file: v2/python.gitlab-ci.yml
 - project: acc-co/devops/python/acc-py-gitlab-ci-templates
   file: v2/acc-py-deploy.gitlab-ci.yml

variables:
  project_name: simple_repository_browser
  PY_VERSION: '3.11'
  ACC_PY_BASE_IMAGE_TAG: '2023.06'


pre-commit:
  extends: .acc_py_pre-commit


fetch_external_deps:
  image: registry.cern.ch/acc/acc-py_el9_ci:pro
  stage: build
  script:
    - yum install -y nodejs npm git
    - pushd javascript
    - npm install --include=dev
    - npm run build
    - popd

    # Build the acc-py repository browser project pre-requisites.
    - ./acc-py-repository-browser/build.sh
    # Get rid of the unnecessary node_modules now we have built the static files.
    - rm -rf ./acc-py-repository-browser/js_build ./acc-py-repository-browser/javascript
  artifacts:
    paths:
     - simple_repository_browser/static/js
     - acc-py-repository-browser/


.acc_py_repo_variables:
  variables:
    project_name: acc_py_repository_browser
    project_root: acc-py-repository-browser/


build_wheel:
  needs:
    - fetch_external_deps
  stage: build
  extends:
    - .acc_py_build_wheel
    - .acc_py_repo_variables


freeze_wheel:
  # Inject the lockfiles from the source directory into the wheel
  extends:
   - .acc_py_freeze_wheel
   - .acc_py_repo_variables
  script:
    - !reference [.acc_py_freeze_wheel, script]
  artifacts:
    paths:
      - ${project_root}/build/acc-py-app-container
      - ${project_root}/dist/*.whl


publish_wheel:
  extends:
    - .acc_py_publish
    - .acc_py_repo_variables
  needs:
    - freeze_wheel
